package com.kazemieh.designsystem.picker

import fintrack.core.designsystem.generated.resources.*

import org.jetbrains.compose.resources.DrawableResource

object FinTrackSourceIcons {

    private val RES_IDS = arrayOf<DrawableResource>(
        Res.drawable.ic_bank_abank,
        Res.drawable.ic_bank_abank_logo,
        Res.drawable.ic_bank_ansar,
        Res.drawable.ic_bank_ayandeh,
        Res.drawable.ic_bank_ayandeh_logo,
        Res.drawable.ic_bank_baam,
        Res.drawable.ic_bank_bajet,
        Res.drawable.ic_bank_bajet_logo,
        Res.drawable.ic_bank_banket,
        Res.drawable.ic_bank_bankino,
        Res.drawable.ic_bank_bankino_logo,
        Res.drawable.ic_bank_bankvareh,
        Res.drawable.ic_bank_baran,
        Res.drawable.ic_bank_baran_logo,
        Res.drawable.ic_bank_blu,
        Res.drawable.ic_bank_blu_jr,
        Res.drawable.ic_bank_blu_jr_logo,
        Res.drawable.ic_bank_blu_logo,
        Res.drawable.ic_bank_central,
        Res.drawable.ic_bank_central_logo,
        Res.drawable.ic_bank_day,
        Res.drawable.ic_bank_day_logo,
        Res.drawable.ic_bank_eghtesad_novin,
        Res.drawable.ic_bank_eghtesad_novin_logo,
        Res.drawable.ic_bank_gardeshgari,
        Res.drawable.ic_bank_gardeshgari_logo,
        Res.drawable.ic_bank_greenbank,
        Res.drawable.ic_bank_greenbank_logo,
        Res.drawable.ic_bank_hibank,
        Res.drawable.ic_bank_hibank_logo,
        Res.drawable.ic_bank_iranzamin,
        Res.drawable.ic_bank_iranzamin_logo,
        Res.drawable.ic_bank_iran_venezuela,
        Res.drawable.ic_bank_iran_venezuela_logo,
        Res.drawable.ic_bank_karafarin,
        Res.drawable.ic_bank_karafarin_logo,
        Res.drawable.ic_bank_keshavarzi,
        Res.drawable.ic_bank_keshavarzi_logo,
        Res.drawable.ic_bank_khavarmianeh,
        Res.drawable.ic_bank_khavarmianeh_logo,
        Res.drawable.ic_bank_maskan,
        Res.drawable.ic_bank_maskan_logo,
        Res.drawable.ic_bank_megabank,
        Res.drawable.ic_bank_mehr,
        Res.drawable.ic_bank_mehr_logo,
        Res.drawable.ic_bank_melal,
        Res.drawable.ic_bank_melal_logo,
        Res.drawable.ic_bank_mellat,
        Res.drawable.ic_bank_mellat_logo,
        Res.drawable.ic_bank_melli,
        Res.drawable.ic_bank_melli_logo,
        Res.drawable.ic_bank_metabank,
        Res.drawable.ic_bank_metabank_logo,
        Res.drawable.ic_bank_noor,
        Res.drawable.ic_bank_noor_logo,
        Res.drawable.ic_bank_omid,
        Res.drawable.ic_bank_omid_logo,
        Res.drawable.ic_bank_parsian,
        Res.drawable.ic_bank_parsian_logo,
        Res.drawable.ic_bank_pasargad,
        Res.drawable.ic_bank_pasargad_logo,
        Res.drawable.ic_bank_postbank,
        Res.drawable.ic_bank_postbank_logo,
        Res.drawable.ic_bank_qbank,
        Res.drawable.ic_bank_qbank_logo,
        Res.drawable.ic_bank_refah,
        Res.drawable.ic_bank_refah_logo,
        Res.drawable.ic_bank_resalat_icon,
        Res.drawable.ic_bank_resalat_logo,
        Res.drawable.ic_bank_saderat,
        Res.drawable.ic_bank_saderat_logo,
        Res.drawable.ic_bank_saman,
        Res.drawable.ic_bank_saman_logo,
        Res.drawable.ic_bank_sanat_maadan,
        Res.drawable.ic_bank_sanat_maadan_logo,
        Res.drawable.ic_bank_sarmayeh,
        Res.drawable.ic_bank_sarmayeh_logo,
        Res.drawable.ic_bank_sepah,
        Res.drawable.ic_bank_sepah_logo,
        Res.drawable.ic_bank_sepino,
        Res.drawable.ic_bank_sepino_logo,
        Res.drawable.ic_bank_shahr,
        Res.drawable.ic_bank_shahr_logo,
        Res.drawable.ic_bank_sibank,
        Res.drawable.ic_bank_sina,
        Res.drawable.ic_bank_sina_logo,
        Res.drawable.ic_bank_tejarat,
        Res.drawable.ic_bank_tejarat_logo,
        Res.drawable.ic_bank_tobank,
        Res.drawable.ic_bank_tobank_logo,
        Res.drawable.ic_bank_tose_saderat,
        Res.drawable.ic_bank_tose_saderat_logo,
        Res.drawable.ic_bank_tose_taavon,
        Res.drawable.ic_bank_tose_taavon_logo,
        Res.drawable.ic_bank_unknown,
        Res.drawable.ic_bank_wepod,
        Res.drawable.ic_bank_wepod_logo
    )

    val icons: List<PickableIcon> by lazy(LazyThreadSafetyMode.NONE) {
        RES_IDS.mapIndexed { index, resId ->
            PickableIcon(id = index + 1000, resource = resId, isTintable = false)
        }
    }
}
