#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.configuration-cache=false
org.gradle.unsafe.configuration-cache=false
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#kotlin.js.nodejs.download=false
#kotlin.js.nodejs.download.baseUrl=https://npmmirror.com/mirrors/node


#
org.gradle.configuration-cache.problems=warn
org.gradle.parallel=true
kotlin.incremental=true
kotlin.incremental.js=true
kotlin.incremental.multiplatform=true
#kotlin.useK2=true
#androidx.compose.compiler.metrics=true
#androidx.compose.compiler.reports=true
org.gradle.daemon=true
org.gradle.workers.max=16
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.native.cacheKind=none