package com.kazemieh.money

object CurrencyProvider {
    val fiatCurrencies = listOf(
        Currency("IRR", "ریال", "currency_name_irr"),
        Currency("IRT", "تومان", "currency_name_irt"),
        Currency("USD", "$", "currency_name_usd"),
        Currency("EUR", "€", "currency_name_eur"),
        Currency("GBP", "£", "currency_name_gbp"),
        Currency("JPY", "¥", "currency_name_jpy"),
        Currency("CNY", "¥", "currency_name_cny"),
        Currency("AUD", "A$", "currency_name_aud"),
        Currency("CAD", "C$", "currency_name_cad"),
        Currency("CHF", "Fr", "currency_name_chf"),
        Currency("AED", "د.إ", "currency_name_aed"),
        Currency("AFN", "؋", "currency_name_afn"),
        Currency("ALL", "L", "currency_name_all"),
        Currency("AMD", "֏", "currency_name_amd"),
        Currency("ANG", "ƒ", "currency_name_ang"),
        Currency("AOA", "Kz", "currency_name_aoa"),
        Currency("ARS", "$", "currency_name_ars"),
        Currency("AWG", "ƒ", "currency_name_awg"),
        Currency("AZN", "₼", "currency_name_azn"),
        Currency("BAM", "KM", "currency_name_bam"),
        Currency("BBD", "$", "currency_name_bbd"),
        Currency("BDT", "৳", "currency_name_bdt"),
        Currency("BGN", "лв", "currency_name_bgn"),
        Currency("BHD", ".د.ب", "currency_name_bhd"),
        Currency("BIF", "FBu", "currency_name_bif"),
        Currency("BMD", "$", "currency_name_bmd"),
        Currency("BND", "$", "currency_name_bnd"),
        Currency("BOB", "Bs.", "currency_name_bob"),
        Currency("BRL", "R$", "currency_name_brl"),
        Currency("BSD", "$", "currency_name_bsd"),
        Currency("BTN", "Nu.", "currency_name_btn"),
        Currency("BWP", "P", "currency_name_bwp"),
        Currency("BYN", "Br", "currency_name_byn"),
        Currency("BZD", "$", "currency_name_bzd"),
        Currency("CDF", "FC", "currency_name_cdf"),
        Currency("CLP", "$", "currency_name_clp"),
        Currency("COP", "$", "currency_name_cop"),
        Currency("CRC", "₡", "currency_name_crc"),
        Currency("CUP", "$", "currency_name_cup"),
        Currency("CVE", "$", "currency_name_cve"),
        Currency("CZK", "Kč", "currency_name_czk"),
        Currency("DJF", "Fdj", "currency_name_djf"),
        Currency("DKK", "kr", "currency_name_dkk"),
        Currency("DOP", "$", "currency_name_dop"),
        Currency("DZD", "د.ج", "currency_name_dzd"),
        Currency("EGP", "E£", "currency_name_egp"),
        Currency("ERN", "Nfk", "currency_name_ern"),
        Currency("ETB", "Br", "currency_name_etb"),
        Currency("FJD", "$", "currency_name_fjd"),
        Currency("FKP", "£", "currency_name_fkp"),
        Currency("GEL", "₾", "currency_name_gel"),
        Currency("GHS", "GH₵", "currency_name_ghs"),
        Currency("GIP", "£", "currency_name_gip"),
        Currency("GMD", "D", "currency_name_gmd"),
        Currency("GNF", "FG", "currency_name_gnf"),
        Currency("GTQ", "Q", "currency_name_gtq"),
        Currency("GYD", "$", "currency_name_gyd"),
        Currency("HKD", "$", "currency_name_hkd"),
        Currency("HNL", "L", "currency_name_hnl"),
        Currency("HTG", "G", "currency_name_htg"),
        Currency("HUF", "Ft", "currency_name_huf"),
        Currency("IDR", "Rp", "currency_name_idr"),
        Currency("ILS", "₪", "currency_name_ils"),
        Currency("INR", "₹", "currency_name_inr"),
        Currency("IQD", "ع.د", "currency_name_iqd"),
        Currency("ISK", "kr", "currency_name_isk"),
        Currency("JMD", "$", "currency_name_jmd"),
        Currency("JOD", "د.ا", "currency_name_jod"),
        Currency("KES", "KSh", "currency_name_kes"),
        Currency("KGS", "с", "currency_name_kgs"),
        Currency("KHR", "៛", "currency_name_khr"),
        Currency("KMF", "CF", "currency_name_kmf"),
        Currency("KPW", "₩", "currency_name_kpw"),
        Currency("KRW", "₩", "currency_name_krw"),
        Currency("KWD", "د.ك", "currency_name_kwd"),
        Currency("KYD", "$", "currency_name_kyd"),
        Currency("KZT", "₸", "currency_name_kzt"),
        Currency("LAK", "₭", "currency_name_lak"),
        Currency("LBP", "L£", "currency_name_lbp"),
        Currency("LKR", "Rs", "currency_name_lkr"),
        Currency("LRD", "$", "currency_name_lrd"),
        Currency("LSL", "L", "currency_name_lsl"),
        Currency("LYD", "ل.د", "currency_name_lyd"),
        Currency("MAD", "د.م.", "currency_name_mad"),
        Currency("MDL", "L", "currency_name_mdl"),
        Currency("MGA", "Ar", "currency_name_mga"),
        Currency("MKD", "ден", "currency_name_mkd"),
        Currency("MMK", "K", "currency_name_mmk"),
        Currency("MNT", "₮", "currency_name_mnt"),
        Currency("MOP", "P", "currency_name_mop"),
        Currency("MRU", "UM", "currency_name_mru"),
        Currency("MUR", "Rs", "currency_name_mur"),
        Currency("MVR", "Rf", "currency_name_mvr"),
        Currency("MWK", "MK", "currency_name_mwk"),
        Currency("MXN", "$", "currency_name_mxn"),
        Currency("MYR", "RM", "currency_name_myr"),
        Currency("MZN", "MT", "currency_name_mzn"),
        Currency("NAD", "$", "currency_name_nad"),
        Currency("NGN", "₦", "currency_name_ngn"),
        Currency("NIO", "C$", "currency_name_nio"),
        Currency("NOK", "kr", "currency_name_nok"),
        Currency("NPR", "Rs", "currency_name_npr"),
        Currency("NZD", "$", "currency_name_nzd"),
        Currency("OMR", "ر.ع.", "currency_name_omr"),
        Currency("PAB", "B/.", "currency_name_pab"),
        Currency("PEN", "S/.", "currency_name_pen"),
        Currency("PGK", "K", "currency_name_pgk"),
        Currency("PHP", "₱", "currency_name_php"),
        Currency("PKR", "Rs", "currency_name_pkr"),
        Currency("PLN", "zł", "currency_name_pln"),
        Currency("PYG", "₲", "currency_name_pyg"),
        Currency("QAR", "ر.ق", "currency_name_qar"),
        Currency("RON", "lei", "currency_name_ron"),
        Currency("RSD", "дин.", "currency_name_rsd"),
        Currency("RUB", "₽", "currency_name_rub"),
        Currency("RWF", "FRw", "currency_name_rwf"),
        Currency("SAR", "ر.س", "currency_name_sar"),
        Currency("SBD", "$", "currency_name_sbd"),
        Currency("SCR", "Rs", "currency_name_scr"),
        Currency("SDG", "ج.س.", "currency_name_sdg"),
        Currency("SEK", "kr", "currency_name_sek"),
        Currency("SGD", "$", "currency_name_sgd"),
        Currency("SHP", "£", "currency_name_shp"),
        Currency("SLE", "Le", "currency_name_sle"),
        Currency("SOS", "Sh", "currency_name_sos"),
        Currency("SRD", "$", "currency_name_srd"),
        Currency("SSP", "£", "currency_name_ssp"),
        Currency("STN", "Db", "currency_name_stn"),
        Currency("SVC", "$", "currency_name_svc"),
        Currency("SYP", "£", "currency_name_syp"),
        Currency("SZL", "L", "currency_name_szl"),
        Currency("THB", "฿", "currency_name_thb"),
        Currency("TJS", "ЅМ", "currency_name_tjs"),
        Currency("TMT", "m", "currency_name_tmt"),
        Currency("TND", "د.ت", "currency_name_tnd"),
        Currency("TOP", "T$", "currency_name_top"),
        Currency("TRY", "₺", "currency_name_try"),
        Currency("TTD", "$", "currency_name_ttd"),
        Currency("TWD", "NT$", "currency_name_twd"),
        Currency("TZS", "Sh", "currency_name_tzs"),
        Currency("UAH", "₴", "currency_name_uah"),
        Currency("UGX", "USh", "currency_name_ugx"),
        Currency("UYU", "$", "currency_name_uyu"),
        Currency("UZS", "so'm", "currency_name_uzs"),
        Currency("VES", "Bs.S", "currency_name_ves"),
        Currency("VND", "₫", "currency_name_vnd"),
        Currency("VUV", "Vt", "currency_name_vuv"),
        Currency("WST", "T", "currency_name_wst"),
        Currency("XAF", "FCFA", "currency_name_xaf"),
        Currency("XCD", "$", "currency_name_xcd"),
        Currency("XOF", "CFA", "currency_name_xof"),
        Currency("XPF", "₣", "currency_name_xpf"),
        Currency("YER", "﷼", "currency_name_yer"),
        Currency("ZAR", "R", "currency_name_zar"),
        Currency("ZMW", "ZK", "currency_name_zmw")
    )

    val cryptocurrencies = listOf(
        Currency("BTC", "₿", "crypto_name_btc", CurrencyType.CRYPTO),
        Currency("ETH", "Ξ", "crypto_name_eth", CurrencyType.CRYPTO),
        Currency("USDT", "₮", "crypto_name_usdt", CurrencyType.CRYPTO),
        Currency("BNB", "BNB", "crypto_name_bnb", CurrencyType.CRYPTO),
        Currency("USDC", "USDC", "crypto_name_usdc", CurrencyType.CRYPTO),
        Currency("XRP", "XRP", "crypto_name_xrp", CurrencyType.CRYPTO),
        Currency("SOL", "SOL", "crypto_name_sol", CurrencyType.CRYPTO),
        Currency("TRX", "TRX", "crypto_name_trx", CurrencyType.CRYPTO),
        Currency("HYPE", "HYPE", "crypto_name_hype", CurrencyType.CRYPTO),
        Currency("DOGE", "Ð", "crypto_name_doge", CurrencyType.CRYPTO),
        Currency("LEO", "LEO", "crypto_name_leo", CurrencyType.CRYPTO),
        Currency("ZEC", "ⓩ", "crypto_name_zec", CurrencyType.CRYPTO),
        Currency("XLM", "XLM", "crypto_name_xlm", CurrencyType.CRYPTO),
        Currency("XMR", "ɱ", "crypto_name_xmr", CurrencyType.CRYPTO),
        Currency("ADA", "ADA", "crypto_name_ada", CurrencyType.CRYPTO),
        Currency("LINK", "LINK", "crypto_name_link", CurrencyType.CRYPTO),
        Currency("NEAR", "NEAR", "crypto_name_near", CurrencyType.CRYPTO),
        Currency("TON", "TON", "crypto_name_ton", CurrencyType.CRYPTO),
        Currency("DOT", "DOT", "crypto_name_dot", CurrencyType.CRYPTO),
        Currency("SHIB", "SHIB", "crypto_name_shib", CurrencyType.CRYPTO),
        Currency("AVAX", "AVAX", "crypto_name_avax", CurrencyType.CRYPTO),
        Currency("STX", "STX", "crypto_name_stx", CurrencyType.CRYPTO),
        Currency("WBTC", "WBTC", "crypto_name_wbtc", CurrencyType.CRYPTO),
        Currency("DAI", "◈", "crypto_name_dai", CurrencyType.CRYPTO),
        Currency("UNI", "UNI", "crypto_name_uni", CurrencyType.CRYPTO),
        Currency("LTC", "Ł", "crypto_name_ltc", CurrencyType.CRYPTO),
        Currency("POL", "POL", "crypto_name_pol", CurrencyType.CRYPTO),
        Currency("BCH", "BCH", "crypto_name_bch", CurrencyType.CRYPTO),
        Currency("ICP", "∞", "crypto_name_icp", CurrencyType.CRYPTO),
        Currency("APT", "APT", "crypto_name_apt", CurrencyType.CRYPTO),
        Currency("RNDR", "RNDR", "crypto_name_rndr", CurrencyType.CRYPTO),
        Currency("HBAR", "ℏ", "crypto_name_hbar", CurrencyType.CRYPTO),
        Currency("ARB", "ARB", "crypto_name_arb", CurrencyType.CRYPTO),
        Currency("KAS", "KAS", "crypto_name_kas", CurrencyType.CRYPTO),
        Currency("FIL", "⨎", "crypto_name_fil", CurrencyType.CRYPTO),
        Currency("IMX", "IMX", "crypto_name_imx", CurrencyType.CRYPTO),
        Currency("OKB", "OKB", "crypto_name_okb", CurrencyType.CRYPTO),
        Currency("MNT", "MNT", "crypto_name_mnt", CurrencyType.CRYPTO),
        Currency("OP", "OP", "crypto_name_op", CurrencyType.CRYPTO),
        Currency("VET", "VET", "crypto_name_vet", CurrencyType.CRYPTO),
        Currency("LDO", "LDO", "crypto_name_ldo", CurrencyType.CRYPTO),
        Currency("GRT", "GRT", "crypto_name_grt", CurrencyType.CRYPTO),
        Currency("RUNE", "ᚱ", "crypto_name_rune", CurrencyType.CRYPTO),
        Currency("THETA", "THETA", "crypto_name_theta", CurrencyType.CRYPTO),
        Currency("INJ", "INJ", "crypto_name_inj", CurrencyType.CRYPTO),
        Currency("TIA", "TIA", "crypto_name_tia", CurrencyType.CRYPTO),
        Currency("TAO", "τ", "crypto_name_tao", CurrencyType.CRYPTO),
        Currency("AR", "AR", "crypto_name_ar", CurrencyType.CRYPTO),
        Currency("BGB", "BGB", "crypto_name_bgb", CurrencyType.CRYPTO)
    )

    val allCurrencies = fiatCurrencies + cryptocurrencies
}
